# @generated by csrc/moe/moe_monokernel/tools/gen_shapes.py from
# csrc/moe/moe_monokernel/shapes.json — DO NOT EDIT BY HAND.


"""Generated monokernel shape registry. Imported by _custom_ops.py and
the tuner. Keys use the FUSED N (2*N_half) as the weight tensors expose it."""

SHAPES = [   {   'key': 'qwen3.5_35b',
        'aliases': ['35b', 'qwen3.5', 'qwen3_5_35b'],
        'E': 256,
        'N_half': 512,
        'K': 2048,
        'N_fused': 1024,
        'default_top_k': 8,
        'display_name': 'Qwen3.5-35B block-wise FP8',
        'cpp': 'E256_N512_K2048',
        'named_op': 'moe_monokernel_topk_BS8_E256_N512_K2048_BlockFP8_WGMMA_TMA',
        'tunable_op': 'moe_monokernel_topk_BS8_E256_N512_K2048_tunable',
        'config_macro': 'MONO_CONFIGS_E256_N512_K2048',
        'configs': {   0: {   'grid': 128,
                              'down_col_tile': 256,
                              'k_step_up': 256,
                              'k_step_down': 256,
                              'up_w_slots': 4,
                              'up_col_halves': 1},
                       1: {   'grid': 128,
                              'down_col_tile': 256,
                              'k_step_up': 128,
                              'k_step_down': 128,
                              'up_w_slots': 4,
                              'up_col_halves': 1},
                       2: {   'grid': 128,
                              'down_col_tile': 256,
                              'k_step_up': 128,
                              'k_step_down': 128,
                              'up_w_slots': 2,
                              'up_col_halves': 1},
                       3: {   'grid': 128,
                              'down_col_tile': 256,
                              'k_step_up': 256,
                              'k_step_down': 256,
                              'up_w_slots': 2,
                              'up_col_halves': 1},
                       4: {   'grid': 128,
                              'down_col_tile': 512,
                              'k_step_up': 256,
                              'k_step_down': 128,
                              'up_w_slots': 2,
                              'up_col_halves': 2},
                       5: {   'grid': 128,
                              'down_col_tile': 512,
                              'k_step_up': 128,
                              'k_step_down': 128,
                              'up_w_slots': 2,
                              'up_col_halves': 2}},
        'raw_upproj_config_ids': [4, 5],
        'all_raw': False},
    {   'key': 'qwen3.5_122b',
        'aliases': ['122b', 'qwen3_5_122b'],
        'E': 256,
        'N_half': 1024,
        'K': 3072,
        'N_fused': 2048,
        'default_top_k': 8,
        'display_name': 'Qwen3.5-122B block-wise FP8',
        'cpp': 'E256_N1024_K3072',
        'named_op': 'moe_monokernel_topk_BS8_E256_N1024_K3072_BlockFP8_WGMMA_TMA',
        'tunable_op': 'moe_monokernel_topk_BS8_E256_N1024_K3072_tunable',
        'config_macro': 'MONO_CONFIGS_E256_N1024_K3072',
        'configs': {   0: {   'grid': 128,
                              'down_col_tile': 384,
                              'k_step_up': 256,
                              'k_step_down': 128,
                              'up_w_slots': 2,
                              'up_col_halves': 2},
                       1: {   'grid': 128,
                              'down_col_tile': 384,
                              'k_step_up': 128,
                              'k_step_down': 128,
                              'up_w_slots': 2,
                              'up_col_halves': 2},
                       2: {   'grid': 128,
                              'down_col_tile': 384,
                              'k_step_up': 128,
                              'k_step_down': 128,
                              'up_w_slots': 4,
                              'up_col_halves': 2}},
        'raw_upproj_config_ids': [0, 1, 2],
        'all_raw': True},
    {   'key': 'e64_n512_k2048',
        'aliases': ['e64'],
        'E': 64,
        'N_half': 512,
        'K': 2048,
        'N_fused': 1024,
        'default_top_k': 8,
        'display_name': 'E-sweep E=64 (N512 K2048) block-wise FP8',
        'cpp': 'E64_N512_K2048',
        'named_op': 'moe_monokernel_topk_BS8_E64_N512_K2048_BlockFP8_WGMMA_TMA',
        'tunable_op': 'moe_monokernel_topk_BS8_E64_N512_K2048_tunable',
        'config_macro': 'MONO_CONFIGS_E64_N512_K2048',
        'configs': {   0: {   'grid': 128,
                              'down_col_tile': 256,
                              'k_step_up': 256,
                              'k_step_down': 256,
                              'up_w_slots': 4,
                              'up_col_halves': 1},
                       1: {   'grid': 128,
                              'down_col_tile': 256,
                              'k_step_up': 128,
                              'k_step_down': 128,
                              'up_w_slots': 4,
                              'up_col_halves': 1},
                       2: {   'grid': 128,
                              'down_col_tile': 256,
                              'k_step_up': 128,
                              'k_step_down': 128,
                              'up_w_slots': 2,
                              'up_col_halves': 1},
                       3: {   'grid': 128,
                              'down_col_tile': 256,
                              'k_step_up': 256,
                              'k_step_down': 256,
                              'up_w_slots': 2,
                              'up_col_halves': 1},
                       4: {   'grid': 128,
                              'down_col_tile': 512,
                              'k_step_up': 256,
                              'k_step_down': 128,
                              'up_w_slots': 2,
                              'up_col_halves': 2},
                       5: {   'grid': 128,
                              'down_col_tile': 512,
                              'k_step_up': 128,
                              'k_step_down': 128,
                              'up_w_slots': 2,
                              'up_col_halves': 2}},
        'raw_upproj_config_ids': [4, 5],
        'all_raw': False},
    {   'key': 'e128_n512_k2048',
        'aliases': ['e128'],
        'E': 128,
        'N_half': 512,
        'K': 2048,
        'N_fused': 1024,
        'default_top_k': 8,
        'display_name': 'E-sweep E=128 (N512 K2048) block-wise FP8',
        'cpp': 'E128_N512_K2048',
        'named_op': 'moe_monokernel_topk_BS8_E128_N512_K2048_BlockFP8_WGMMA_TMA',
        'tunable_op': 'moe_monokernel_topk_BS8_E128_N512_K2048_tunable',
        'config_macro': 'MONO_CONFIGS_E128_N512_K2048',
        'configs': {   0: {   'grid': 128,
                              'down_col_tile': 256,
                              'k_step_up': 256,
                              'k_step_down': 256,
                              'up_w_slots': 4,
                              'up_col_halves': 1},
                       1: {   'grid': 128,
                              'down_col_tile': 256,
                              'k_step_up': 128,
                              'k_step_down': 128,
                              'up_w_slots': 4,
                              'up_col_halves': 1},
                       2: {   'grid': 128,
                              'down_col_tile': 256,
                              'k_step_up': 128,
                              'k_step_down': 128,
                              'up_w_slots': 2,
                              'up_col_halves': 1},
                       3: {   'grid': 128,
                              'down_col_tile': 256,
                              'k_step_up': 256,
                              'k_step_down': 256,
                              'up_w_slots': 2,
                              'up_col_halves': 1},
                       4: {   'grid': 128,
                              'down_col_tile': 512,
                              'k_step_up': 256,
                              'k_step_down': 128,
                              'up_w_slots': 2,
                              'up_col_halves': 2},
                       5: {   'grid': 128,
                              'down_col_tile': 512,
                              'k_step_up': 128,
                              'k_step_down': 128,
                              'up_w_slots': 2,
                              'up_col_halves': 2}},
        'raw_upproj_config_ids': [4, 5],
        'all_raw': False},
    {   'key': 'e512_n512_k2048',
        'aliases': ['e512'],
        'E': 512,
        'N_half': 512,
        'K': 2048,
        'N_fused': 1024,
        'default_top_k': 8,
        'display_name': 'E-sweep E=512 (N512 K2048) block-wise FP8',
        'cpp': 'E512_N512_K2048',
        'named_op': 'moe_monokernel_topk_BS8_E512_N512_K2048_BlockFP8_WGMMA_TMA',
        'tunable_op': 'moe_monokernel_topk_BS8_E512_N512_K2048_tunable',
        'config_macro': 'MONO_CONFIGS_E512_N512_K2048',
        'configs': {   0: {   'grid': 128,
                              'down_col_tile': 256,
                              'k_step_up': 256,
                              'k_step_down': 256,
                              'up_w_slots': 4,
                              'up_col_halves': 1},
                       1: {   'grid': 128,
                              'down_col_tile': 256,
                              'k_step_up': 128,
                              'k_step_down': 128,
                              'up_w_slots': 4,
                              'up_col_halves': 1},
                       2: {   'grid': 128,
                              'down_col_tile': 256,
                              'k_step_up': 128,
                              'k_step_down': 128,
                              'up_w_slots': 2,
                              'up_col_halves': 1},
                       3: {   'grid': 128,
                              'down_col_tile': 256,
                              'k_step_up': 256,
                              'k_step_down': 256,
                              'up_w_slots': 2,
                              'up_col_halves': 1},
                       4: {   'grid': 128,
                              'down_col_tile': 512,
                              'k_step_up': 256,
                              'k_step_down': 128,
                              'up_w_slots': 2,
                              'up_col_halves': 2},
                       5: {   'grid': 128,
                              'down_col_tile': 512,
                              'k_step_up': 128,
                              'k_step_down': 128,
                              'up_w_slots': 2,
                              'up_col_halves': 2}},
        'raw_upproj_config_ids': [4, 5],
        'all_raw': False}]

# (E, N_fused, K) -> row, for O(1) dispatch.
BY_ENK = {(r['E'], r['N_fused'], r['K']): r for r in SHAPES}
# alias / shape-name -> row (e.g. '35b', 'qwen3.5_122b').
BY_NAME = {a: r for r in SHAPES for a in ([r['key']] + r['aliases'])}


def row_for(E, N_fused, K):
    """Registry row for a fused-(E, N, K) shape, or None if unsupported.
    N_fused is the gate+up dim (2 * moe_intermediate_size)."""
    return BY_ENK.get((E, N_fused, K))


def is_supported(E, N_fused, K):
    return (E, N_fused, K) in BY_ENK


def named_op_name(E, N_fused, K):
    r = BY_ENK[(E, N_fused, K)]
    return r["named_op"]


def tunable_op_name(E, N_fused, K):
    r = BY_ENK[(E, N_fused, K)]
    return r["tunable_op"]


def config_is_raw_upproj(E, N_fused, K, config_id):
    """True if the selected config uses the raw two-TMA up-proj (UCH>=2) and
    therefore must NOT be fed Python-interleaved weights.  Shape-agnostic:
    derived from the registry's per-shape raw-config-id set."""
    if config_id is None or config_id < 0:
        return False
    r = BY_ENK.get((E, N_fused, K))
    if r is None:
        return False
    return r["all_raw"] or (config_id in set(r["raw_upproj_config_ids"]))


def resolve_config_id(E, N_fused, K, env_value):
    """Parse a MONOKERNEL_CONFIG env string into a config id for this shape.
    Forms: bare int (any shape) | name:id (35b/122b/...) | E{E}N{N}K{K}:id
    (N here is N_fused).  Returns -1 (shipped default) if unset/unmatched."""
    raw = (env_value or "").strip()
    if not raw:
        return -1
    if raw.lstrip("-").isdigit():
        return int(raw)
    r = BY_ENK.get((E, N_fused, K))
    names = set()
    if r is not None:
        names = {r["key"].lower(), *[a.lower() for a in r["aliases"]]}
    enk_key = f"e{E}n{N_fused}k{K}"
    for part in raw.split(","):
        if ":" not in part:
            continue
        key, _, val = part.partition(":")
        key = key.strip().lower()
        if key in names or key == enk_key:
            if val.strip().lstrip("-").isdigit():
                return int(val.strip())
    return -1
