#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project
"""Monokernel shape code generator.

Single source of truth: ``csrc/moe/moe_monokernel/shapes.json``.  The kernel is
template-specialized on (N, K, E) at compile time, so every distinct shape needs
its own ``Dims`` instantiation + op symbol + bindings + dispatch + tuner entry.
Hand-maintaining those across files is error-prone; this script emits them all
from the one table.

Outputs (written under ``csrc/moe/moe_monokernel/generated/``) — each is an
``#include`` / ``import`` consumed by a hand-written source, so regeneration
never rewrites hand code:

  dims_generated.inc       — Dims_* structs (+ legacy `using` aliases)
  wrapper_generated.inc    — MOEMONOKERNEL_TOPK_WRAPPER_IMPLEMENTATION,
                             MONO_CONFIGS_* X-macro tables, dispatch_tunable_*,
                             *_tunable_impl bodies
  ops_generated.inc        — op + tunable-op forward declarations
  defs_generated.inc       — torch m.def schemas (stable-ABI fragment)
  impls_generated.inc      — torch m.impl registrations (full-libtorch
                             TORCH_LIBRARY_IMPL in moe_wrapper.cu)
  monokernel_shapes.py     — Python dispatch table (E,N,K)->op names + raw-upproj
                             config-id sets + tuner SHAPE / MODELS metadata

Naming: shape-keyed ``E{E}_N{N}_K{K}`` is canonical; a shape's ``legacy_cpp_name``
(e.g. ``Qwen3_5_35B``) gets a C++ ``using`` alias and the legacy op symbols so
existing callers keep working.

Usage:
  gen_shapes.py                 # regenerate all outputs
  gen_shapes.py --check         # exit 1 if outputs are stale (CI guard)
  gen_shapes.py --print dims    # print one section to stdout (debug)
"""

import argparse
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", "..", "..", ".."))  # repo root
MONO = os.path.normpath(os.path.join(HERE, ".."))  # moe_monokernel/
SHAPES_JSON = os.path.join(MONO, "shapes.json")
GEN_DIR = os.path.join(MONO, "generated")  # C++ .inc files (#included by sources)
# The Python registry must be importable from the installed `vllm` package
# (serving + tuner run outside the repo root), so it lands next to the other
# fused_moe Python helpers rather than under csrc/.
PY_PKG_DIR = os.path.join(ROOT, "vllm", "model_executor", "layers", "fused_moe")
ATOM = 128
WGMMA_K = 128

GEN_HEADER = (
    "// @generated by csrc/moe/moe_monokernel/tools/gen_shapes.py from\n"
    "// csrc/moe/moe_monokernel/shapes.json — DO NOT EDIT BY HAND.\n"
    "// Re-run gen_shapes.py after editing shapes.json.\n\n"
)
PY_GEN_HEADER = (
    "# SPDX-License-Identifier: Apache-2.0\n"
    "# SPDX-FileCopyrightText: Copyright contributors to the vLLM project\n"
    "# @generated by csrc/moe/moe_monokernel/tools/gen_shapes.py from\n"
    "# csrc/moe/moe_monokernel/shapes.json — DO NOT EDIT BY HAND.\n\n"
)


def cpp_name(shape):
    """Canonical shape-keyed C++ Dims/op infix: E{E}_N{N}_K{K}."""
    return f"E{shape['E']}_N{shape['N']}_K{shape['K']}"


def legacy_infix(shape):
    """Legacy op/Dims infix (e.g. E256_Qwen3_5_35B) or None.  Kept as a
    back-compat alias so existing Python/test callers that reference the old
    symbol names keep working after the switch to shape-keyed canonical names."""
    lc = shape.get("legacy_cpp_name")
    return f"E{shape['E']}_{lc}" if lc else None


def uch_of(shape, dct, cfg=None):
    """UP_COL_HALVES for a shape/config.

    DECOUPLED shapes pin an explicit `up_col_halves` (the up/down grids are
    chosen independently, so UCH does not follow the DCT coupling identity);
    return it verbatim.  Individual configs may also set `uch` to test a
    decoupled/raw carve without making the whole shape raw.  Otherwise,
    COUPLED shapes derive UCH = max(1, 2*N*DCT/(128*K)), mirroring the C++
    `up_col_halves<Dims>` fallback.  `dct` is per-config so a coupled shape
    with mixed DCT (e.g. 35B cfg4/5 at DCT=512) reports the right UCH per
    config."""
    if cfg is not None and cfg.get("uch") is not None:
        return int(cfg["uch"])
    if shape.get("up_col_halves") is not None:
        return int(shape["up_col_halves"])
    v = (2 * shape["N"] * dct) // (ATOM * shape["K"])
    return v if v > 0 else 1


def load_shapes():
    with open(SHAPES_JSON) as f:
        data = json.load(f)
    shapes = data["shapes"]
    # Validate constraints early — a bad shape should fail here, not at nvcc.
    seen_keys, seen_enk = set(), set()
    for s in shapes:
        E, N, K = s["E"], s["N"], s["K"]
        assert E % 32 == 0, f"{s['key']}: E={E} must be a multiple of 32"
        assert N % ATOM == 0, f"{s['key']}: N={N} must be a multiple of 128"
        assert K % ATOM == 0, f"{s['key']}: K={K} must be a multiple of 128"
        assert s["default_top_k"] <= 8, f"{s['key']}: default_top_k must be <= 8"
        assert s["configs"], f"{s['key']}: needs at least config 0"
        assert s["configs"][0]["id"] == 0, f"{s['key']}: config 0 must be the default"
        ids = [c["id"] for c in s["configs"]]
        assert ids == sorted(set(ids)), f"{s['key']}: config ids must be unique/sorted"
        assert s["key"] not in seen_keys, f"duplicate shape key {s['key']}"
        seen_keys.add(s["key"])
        enk = (E, N, K)
        assert enk not in seen_enk, f"duplicate (E,N,K)={enk}"
        seen_enk.add(enk)
    return data


# ── C++ section emitters ────────────────────────────────────────────────────


def emit_dims(shapes):
    """Dims_* structs.  The base struct's KernelConfig knobs come from the
    shape's config[0] (the shipped default), so the base Dims and the config-0
    tunable instantiation are byte-identical — preserving the zero-regression
    contract.  UP_COL_HALVES is derived (not stored); DOWN_COL_TILE is emitted
    only when it differs from the kernel's own default detection (i.e. when the
    default config's dct implies UCH>=2, the kernel needs DOWN_COL_TILE set)."""
    out = [GEN_HEADER]
    for s in shapes:
        nm = cpp_name(s)
        c0 = s["configs"][0]
        uch = uch_of(s, c0["dct"], c0)
        struct = f"Dims_BS8_{nm}_BlockFP8_WGMMA_TMA"
        out.append(
            f"// {s['display_name']}  (E={s['E']} N={s['N']} K={s['K']}, "
            f"default cfg0: grid={c0['grid']} DCT={c0['dct']} "
            f"KUP={c0['kup']} KDN={c0['kdn']} SLOTS={c0['slots']} "
            f"=> UP_COL_HALVES={uch})"
        )
        out.append(f"struct {struct} {{")
        out.append(f"  static constexpr uint32_t HIDDEN_STATES = {s['K']};")
        out.append(f"  static constexpr uint32_t K = {s['K']};")
        out.append(f"  static constexpr uint32_t N = {s['N']};")
        out.append("  static constexpr uint32_t BS = 8;")
        out.append("  static constexpr uint32_t M = 8;")
        out.append(f"  static constexpr uint32_t NUM_EXPERTS = {s['E']};")
        out.append(
            "  static constexpr QuantGranularity QUANT_GRAN = "
            "QuantGranularity::BLOCK_WISE;"
        )
        out.append("  static constexpr uint32_t BLOCK_SCALE_ROW = 128;")
        out.append("  static constexpr uint32_t BLOCK_SCALE_COL = 128;")
        out.append(
            "  static constexpr uint32_t UP_SCALE_ROWS =\n"
            "      (2 * N + BLOCK_SCALE_ROW - 1) / BLOCK_SCALE_ROW;"
        )
        out.append(
            "  static constexpr uint32_t UP_SCALE_COLS =\n"
            "      (K + BLOCK_SCALE_COL - 1) / BLOCK_SCALE_COL;"
        )
        out.append(
            "  static constexpr uint32_t DOWN_SCALE_ROWS =\n"
            "      (K + BLOCK_SCALE_ROW - 1) / BLOCK_SCALE_ROW;"
        )
        out.append(
            "  static constexpr uint32_t DOWN_SCALE_COLS =\n"
            "      (N + BLOCK_SCALE_COL - 1) / BLOCK_SCALE_COL;"
        )
        out.append("  struct KernelConfig {")
        out.append(f"    static constexpr std::uint32_t GRID_SIZE = {c0['grid']};")
        out.append("    static constexpr std::uint32_t BLOCK_SIZE = 384;")
        out.append("    static constexpr bool USE_WGMMA = true;")
        out.append("    static constexpr bool USE_TMA = true;")
        out.append(f"    static constexpr std::uint32_t K_STEP_DOWN = {c0['kdn']};")
        out.append(f"    static constexpr std::uint32_t K_STEP_UP = {c0['kup']};")
        # DOWN_COL_TILE: the kernel derives a per-shape default, but when the
        # default differs from HIDDEN/GRID*... the shape pins it.  We always
        # emit it when UCH>=2 (raw path needs the explicit tile), matching the
        # hand-written 122B which set DOWN_COL_TILE=384.  For UCH==1 shapes the
        # hand code omitted it (kernel default), so we omit too.
        if uch >= 2:
            out.append(
                f"    static constexpr std::uint32_t DOWN_COL_TILE = {c0['dct']};"
            )
        # UP_COL_HALVES: pinned ONLY for decoupled shapes (explicit
        # `up_col_halves` in shapes.json).  Coupled shapes leave it absent so
        # the kernel derives it from DOWN_COL_TILE (byte-identical to the
        # pre-knob behavior).  When present it decouples the up-grid carve
        # from DCT, which is what lets UP_GROUPS != DOWN_GROUPS.
        if s.get("up_col_halves") is not None:
            out.append(
                f"    static constexpr std::uint32_t UP_COL_HALVES = "
                f"{int(s['up_col_halves'])};"
            )
        # SLOTS: omit when it equals the shape's natural default (4 for UCH==1,
        # 2 for UCH>=2) so we reproduce the hand code, which relied on the
        # up_w_slots<Dims> default.  Emit explicitly otherwise.
        #
        # DECOUPLED shapes (explicit up_col_halves) MUST always emit it: the
        # `up_w_slots<Dims>` C++ fallback derives the "natural" depth from the
        # DCT coupling identity (2*N*DCT/(128*K)), which floors to 0 for a
        # decoupled shape and would wrongly return 4 — making the base named
        # op differ from the config-0 tunable op.  Emitting it verbatim keeps
        # the zero-regression base==config0 contract.
        natural_slots = 4 if uch == 1 else 2
        if c0["slots"] != natural_slots or s.get("up_col_halves") is not None:
            out.append(
                f"    static constexpr std::uint32_t UP_W_SLOTS = {c0['slots']};"
            )
        out.append("    static constexpr bool USE_PAIR_LAYOUT = true;")
        out.append("  };")
        out.append("};")
        # Legacy alias so existing C++ references keep compiling.
        if s.get("legacy_cpp_name"):
            # Build the exact legacy struct name from the recorded token.
            legacy = f"Dims_BS8_E{s['E']}_{s['legacy_cpp_name']}_BlockFP8_WGMMA_TMA"
            out.append(f"using {legacy} = {struct};")
        # BS16 companion tag: identical KernelConfig knobs (config-0), BS
        # and M doubled to 16.  The kernel template body is shared with
        # BS8 (moe_kernel_topk_BS8); host dispatch selects the BS16 op for
        # 8 < token_count <= 16.  Opt-in per shape via `"bs16": true`.
        if s.get("bs16"):
            struct16 = f"Dims_BS16_{nm}_BlockFP8_WGMMA_TMA"
            out.append(
                f"// BS16 companion of {struct} — selected for token_count in (8, 16]."
            )
            out.append(f"struct {struct16} {{")
            out.append(f"  static constexpr uint32_t HIDDEN_STATES = {s['K']};")
            out.append(f"  static constexpr uint32_t K = {s['K']};")
            out.append(f"  static constexpr uint32_t N = {s['N']};")
            out.append("  static constexpr uint32_t BS = 16;")
            out.append("  static constexpr uint32_t M = 16;")
            out.append(f"  static constexpr uint32_t NUM_EXPERTS = {s['E']};")
            out.append(
                "  static constexpr QuantGranularity QUANT_GRAN = "
                "QuantGranularity::BLOCK_WISE;"
            )
            out.append("  static constexpr uint32_t BLOCK_SCALE_ROW = 128;")
            out.append("  static constexpr uint32_t BLOCK_SCALE_COL = 128;")
            out.append(
                "  static constexpr uint32_t UP_SCALE_ROWS =\n"
                "      (2 * N + BLOCK_SCALE_ROW - 1) / BLOCK_SCALE_ROW;"
            )
            out.append(
                "  static constexpr uint32_t UP_SCALE_COLS =\n"
                "      (K + BLOCK_SCALE_COL - 1) / BLOCK_SCALE_COL;"
            )
            out.append(
                "  static constexpr uint32_t DOWN_SCALE_ROWS =\n"
                "      (K + BLOCK_SCALE_ROW - 1) / BLOCK_SCALE_ROW;"
            )
            out.append(
                "  static constexpr uint32_t DOWN_SCALE_COLS =\n"
                "      (N + BLOCK_SCALE_COL - 1) / BLOCK_SCALE_COL;"
            )
            out.append("  struct KernelConfig {")
            out.append(f"    static constexpr std::uint32_t GRID_SIZE = {c0['grid']};")
            out.append("    static constexpr std::uint32_t BLOCK_SIZE = 384;")
            out.append("    static constexpr bool USE_WGMMA = true;")
            out.append("    static constexpr bool USE_TMA = true;")
            out.append(f"    static constexpr std::uint32_t K_STEP_DOWN = {c0['kdn']};")
            out.append(f"    static constexpr std::uint32_t K_STEP_UP = {c0['kup']};")
            if uch >= 2:
                out.append(
                    f"    static constexpr std::uint32_t DOWN_COL_TILE = {c0['dct']};"
                )
            if s.get("up_col_halves") is not None:
                out.append(
                    f"    static constexpr std::uint32_t UP_COL_HALVES"
                    f" = {int(s['up_col_halves'])};"
                )
            natural_slots16 = 4 if uch == 1 else 2
            if c0["slots"] != natural_slots16 or s.get("up_col_halves") is not None:
                out.append(
                    f"    static constexpr std::uint32_t UP_W_SLOTS = {c0['slots']};"
                )
            out.append("    static constexpr bool USE_PAIR_LAYOUT = true;")
            out.append("  };")
            out.append("};")
        out.append("")
    return "\n".join(out)


def bs16_config_ids(s):
    """Config ids to instantiate for the BS16 tunable dispatcher.

    Defaults to all configs for a bs16-enabled shape, but shapes may restrict
    this when some BS8 candidates exceed the larger BS16 shared-memory layout.
    """
    if not s.get("bs16"):
        return []
    if s.get("bs16_config_ids") is not None:
        return list(s["bs16_config_ids"])
    return [c["id"] for c in s["configs"]]


def config_uch_arg(c):
    """Explicit UCH template arg for DimsTunable; 0 means derive/preserve."""
    return int(c.get("uch", 0) or 0)


def config_dpd_arg(c):
    """Explicit activation DOWN_PIPE_DEPTH; 0 means classic depth 2."""
    return int(c.get("dpd", 0) or 0)


def config_dws_arg(c):
    """Explicit DOWN_WEIGHT_SLOTS; 0 inherits effective activation depth."""
    return int(c.get("dws", 0) or 0)


def config_x_line(c):
    note = f"  /* {c['note']} */" if c.get("note") else ""
    return (
        f"  X({c['id']}, {c['grid']}, {c['dct']}, {c['kup']}, "
        f"{c['kdn']}, {c['slots']}, {config_uch_arg(c)}, "
        f"{config_dpd_arg(c)}, {config_dws_arg(c)}){note}"
    )


def emit_config_table(shapes):
    """MONO_CONFIGS_<KEY>(X) X-macro tables.

    Columns: id, GRID, DCT, KUP, KDN, SLOTS, explicit UCH (0 =
    derive/preserve), activation DPD (0 = 2), and independent down-weight
    slots DWS (0 = inherit DPD).
    """
    out = [GEN_HEADER]
    for s in shapes:
        nm = cpp_name(s)
        out.append(f"#define MONO_CONFIGS_{nm}(X) \\")
        out.append(" \\\n".join(config_x_line(c) for c in s["configs"]))
        out.append("")
        ids16 = set(bs16_config_ids(s))
        if ids16:
            out.append(f"#define MONO_CONFIGS_BS16_{nm}(X) \\")
            out.append(
                " \\\n".join(config_x_line(c) for c in s["configs"] if c["id"] in ids16)
            )
            out.append("")
    return "\n".join(out)


def emit_wrapper(shapes):
    """Named wrapper impls + dispatch_tunable_<key> + *_tunable_impl bodies."""
    out = [GEN_HEADER]
    for s in shapes:
        nm = cpp_name(s)
        struct = f"moe_monokernel::Dims_BS8_{nm}_BlockFP8_WGMMA_TMA"
        out.append("MOEMONOKERNEL_TOPK_WRAPPER_IMPLEMENTATION(")
        out.append(f"    moe_monokernel_topk_BS8_{nm}_BlockFP8_WGMMA_TMA_impl,")
        out.append(f"    {struct})")
        out.append("")
        if s.get("bs16"):
            struct16 = f"moe_monokernel::Dims_BS16_{nm}_BlockFP8_WGMMA_TMA"
            out.append("// BS16 instantiation: reuses the moe_kernel_topk")
            out.append("// template body; selected by host dispatch for")
            out.append("// 8 < token_count <= 16.")
            out.append("MOEMONOKERNEL_TOPK_WRAPPER_IMPLEMENTATION(")
            out.append(f"    moe_monokernel_topk_BS16_{nm}_BlockFP8_WGMMA_TMA_impl,")
            out.append(f"    {struct16})")
            out.append("")
    # dispatch helpers live in the moe_monokernel namespace
    out.append("namespace moe_monokernel {")
    for s in shapes:
        nm = cpp_name(s)
        out.append("template <typename Base>")
        out.append(f"static inline void dispatch_tunable_{nm}(")
        out.append("    const torch::Tensor& ai, const torch::Tensor& rl,")
        out.append("    const torch::Tensor& ewu, const torch::Tensor& esu,")
        out.append(
            "    const torch::Tensor& ewd, const torch::Tensor& esd, torch::Tensor& ao,"
        )
        out.append("    torch::Tensor& sp, int64_t top_k, int64_t sf, bool renorm,")
        out.append("    const std::optional<torch::Tensor>& eb, double rsf,")
        out.append("    int64_t config_id) {")
        out.append("#define X(ID, GRID, DCT, KUP, KDN, SLOTS, UCH, DPD, DWS) " + "\\")
        out.append("  case ID:                                              " + "\\")
        out.append(
            "    launch_moe_monokernel<DimsTunable<Base, GRID, DCT, KUP, "
            "KDN, SLOTS, UCH, DPD, DWS>>(  " + "\\"
        )
        out.append(
            "        ai, rl, ewu, esu, ewd, esd, ao, sp, top_k, sf, renorm, "
            "eb, rsf,       " + "\\"
        )
        out.append(
            f'        "{nm}_cfg" #ID);                                             \\'
        )
        out.append("    return;")
        out.append("  switch (config_id) {")
        out.append(f"    MONO_CONFIGS_{nm}(X)")
        out.append("    default:")
        out.append(
            f'      TORCH_CHECK(false, "moe_monokernel {nm}: unknown '
            'config_id ", config_id);'
        )
        out.append("  }")
        out.append("#undef X")
        out.append("}")
        out.append("")
        if bs16_config_ids(s):
            out.append("template <typename Base>")
            out.append(f"static inline void dispatch_tunable_BS16_{nm}(")
            out.append("    const torch::Tensor& ai, const torch::Tensor& rl,")
            out.append("    const torch::Tensor& ewu, const torch::Tensor& esu,")
            out.append(
                "    const torch::Tensor& ewd, const torch::Tensor& esd, "
                "torch::Tensor& ao,"
            )
            out.append("    torch::Tensor& sp, int64_t top_k, int64_t sf, bool renorm,")
            out.append("    const std::optional<torch::Tensor>& eb, double rsf,")
            out.append("    int64_t config_id) {")
            out.append(
                "#define X(ID, GRID, DCT, KUP, KDN, SLOTS, UCH, DPD, DWS) " + "\\"
            )
            out.append(
                "  case ID:                                              " + "\\"
            )
            out.append(
                "    launch_moe_monokernel<DimsTunable<Base, GRID, DCT, KUP, "
                "KDN, SLOTS, UCH, DPD, DWS>>(  " + "\\"
            )
            out.append(
                "        ai, rl, ewu, esu, ewd, esd, ao, sp, top_k, sf, renorm, "
                "eb, rsf,       " + "\\"
            )
            out.append(
                f'        "{nm}_bs16_cfg" #ID);                                  \\'
            )
            out.append("    return;")
            out.append("  switch (config_id) {")
            out.append(f"    MONO_CONFIGS_BS16_{nm}(X)")
            out.append("    default:")
            out.append(
                f'      TORCH_CHECK(false, "moe_monokernel BS16 {nm}: unknown '
                'or unsupported config_id ", config_id);'
            )
            out.append("  }")
            out.append("#undef X")
            out.append("}")
            out.append("")
    out.append("}  // namespace moe_monokernel")
    out.append("")
    # tunable_impl free functions
    for s in shapes:
        nm = cpp_name(s)
        out.append(f"void moe_monokernel_topk_BS8_{nm}_tunable_impl(")
        out.append(
            "    const torch::Tensor& activations_in, const torch::Tensor& "
            "router_logits,"
        )
        out.append("    const torch::Tensor& expert_weights_up,")
        out.append("    const torch::Tensor& expert_scales_up,")
        out.append("    const torch::Tensor& expert_weights_down,")
        out.append(
            "    const torch::Tensor& expert_scales_down, torch::Tensor& "
            "activations_out,"
        )
        out.append(
            "    torch::Tensor& scratchpad, int64_t top_k, int64_t scoring_func,"
        )
        out.append("    bool renormalize,")
        out.append("    const std::optional<torch::Tensor>& expert_bias,")
        out.append("    double routed_scaling_factor, int64_t config_id) {")
        out.append(f"  moe_monokernel::dispatch_tunable_{nm}<")
        out.append(f"      moe_monokernel::Dims_BS8_{nm}_BlockFP8_WGMMA_TMA>(")
        out.append(
            "      activations_in, router_logits, expert_weights_up, expert_scales_up,"
        )
        out.append(
            "      expert_weights_down, expert_scales_down, activations_out, "
            "scratchpad,"
        )
        out.append(
            "      top_k, scoring_func, renormalize, expert_bias, "
            "routed_scaling_factor,"
        )
        out.append("      config_id);")
        out.append("}")
        out.append("")
        if s.get("bs16"):
            out.append(f"void moe_monokernel_topk_BS16_{nm}_tunable_impl(")
            out.append(
                "    const torch::Tensor& activations_in, const torch::Tensor& "
                "router_logits,"
            )
            out.append("    const torch::Tensor& expert_weights_up,")
            out.append("    const torch::Tensor& expert_scales_up,")
            out.append("    const torch::Tensor& expert_weights_down,")
            out.append(
                "    const torch::Tensor& expert_scales_down, torch::Tensor& "
                "activations_out,"
            )
            out.append(
                "    torch::Tensor& scratchpad, int64_t top_k, int64_t scoring_func,"
            )
            out.append("    bool renormalize,")
            out.append("    const std::optional<torch::Tensor>& expert_bias,")
            out.append("    double routed_scaling_factor, int64_t config_id) {")
            out.append(f"  moe_monokernel::dispatch_tunable_BS16_{nm}<")
            out.append(f"      moe_monokernel::Dims_BS16_{nm}_BlockFP8_WGMMA_TMA>(")
            out.append(
                "      activations_in, router_logits, expert_weights_up, "
                "expert_scales_up,"
            )
            out.append(
                "      expert_weights_down, expert_scales_down, activations_out, "
                "scratchpad,"
            )
            out.append(
                "      top_k, scoring_func, renormalize, expert_bias, "
                "routed_scaling_factor,"
            )
            out.append("      config_id);")
            out.append("}")
            out.append("")
    # Legacy-name forwarders: thin wrappers so old op symbols keep resolving.
    for s in shapes:
        leg = legacy_infix(s)
        if not leg:
            continue
        nm = cpp_name(s)
        # named legacy op -> shape-keyed named impl
        out.append(f"// Legacy alias ops for {leg} -> canonical {nm}.")
        out.append(f"void moe_monokernel_topk_BS8_{leg}_BlockFP8_WGMMA_TMA_impl(")
        out.append("    const torch::Tensor& ai, const torch::Tensor& rl,")
        out.append("    const torch::Tensor& ewu, const torch::Tensor& esu,")
        out.append("    const torch::Tensor& ewd, const torch::Tensor& esd,")
        out.append("    torch::Tensor& ao, torch::Tensor& sp, int64_t top_k,")
        out.append("    int64_t scoring_func, bool renormalize,")
        out.append("    const std::optional<torch::Tensor>& expert_bias,")
        out.append("    double routed_scaling_factor) {")
        out.append(f"  moe_monokernel_topk_BS8_{nm}_BlockFP8_WGMMA_TMA_impl(")
        out.append("      ai, rl, ewu, esu, ewd, esd, ao, sp, top_k, scoring_func,")
        out.append("      renormalize, expert_bias, routed_scaling_factor);")
        out.append("}")
        out.append(f"void moe_monokernel_topk_BS8_{leg}_tunable_impl(")
        out.append("    const torch::Tensor& ai, const torch::Tensor& rl,")
        out.append("    const torch::Tensor& ewu, const torch::Tensor& esu,")
        out.append("    const torch::Tensor& ewd, const torch::Tensor& esd,")
        out.append("    torch::Tensor& ao, torch::Tensor& sp, int64_t top_k,")
        out.append("    int64_t scoring_func, bool renormalize,")
        out.append("    const std::optional<torch::Tensor>& expert_bias,")
        out.append("    double routed_scaling_factor, int64_t config_id) {")
        out.append(f"  moe_monokernel_topk_BS8_{nm}_tunable_impl(")
        out.append("      ai, rl, ewu, esu, ewd, esd, ao, sp, top_k, scoring_func,")
        out.append("      renormalize, expert_bias, routed_scaling_factor, config_id);")
        out.append("}")
        out.append("")
    return _stableize("\n".join(out))


def _stableize(code: str) -> str:
    """Rewrite generated C++ for the stable-ABI build.

    moe_wrapper.cu and these generated includes compile into
    _moe_C_stable_libtorch (TORCH_TARGET_VERSION defined), which forbids
    full-libtorch headers and types.  The hand-written wrapper already uses
    torch::stable::Tensor / STD_TORCH_CHECK; mirror that in the generated code
    so the two interoperate.  Replacing torch::Tensor (not torch::stable::*)
    is safe because the generator never emits torch::stable directly.
    """
    code = code.replace("torch::Tensor", "torch::stable::Tensor")
    code = code.replace("TORCH_CHECK(", "STD_TORCH_CHECK(")
    return code


def _op_decl(symbol, tunable):
    extra = ", int64_t config_id" if tunable else ""
    return (
        f"void {symbol}(\n"
        "    const torch::Tensor& activations_in, const torch::Tensor& "
        "router_logits,\n"
        "    const torch::Tensor& expert_weights_up,\n"
        "    const torch::Tensor& expert_scales_up,\n"
        "    const torch::Tensor& expert_weights_down,\n"
        "    const torch::Tensor& expert_scales_down, torch::Tensor& "
        "activations_out,\n"
        "    torch::Tensor& scratchpad, int64_t top_k, int64_t scoring_func,\n"
        "    bool renormalize,\n"
        "    const std::optional<torch::Tensor>& expert_bias,\n"
        f"    double routed_scaling_factor{extra});\n"
    )


def emit_ops(shapes):
    out = [GEN_HEADER]
    for s in shapes:
        nm = cpp_name(s)
        out.append(
            _op_decl(
                f"moe_monokernel_topk_BS8_{nm}_BlockFP8_WGMMA_TMA_impl", tunable=False
            )
        )
        out.append(_op_decl(f"moe_monokernel_topk_BS8_{nm}_tunable_impl", tunable=True))
        if s.get("bs16"):
            out.append(
                _op_decl(
                    f"moe_monokernel_topk_BS16_{nm}_BlockFP8_WGMMA_TMA_impl",
                    tunable=False,
                )
            )
            out.append(
                _op_decl(f"moe_monokernel_topk_BS16_{nm}_tunable_impl", tunable=True)
            )
        leg = legacy_infix(s)
        if leg:
            out.append(
                _op_decl(
                    f"moe_monokernel_topk_BS8_{leg}_BlockFP8_WGMMA_TMA_impl",
                    tunable=False,
                )
            )
            out.append(
                _op_decl(f"moe_monokernel_topk_BS8_{leg}_tunable_impl", tunable=True)
            )
    return _stableize("\n".join(out))


def _def(symbol, tunable):
    """The m.def schema for one op.  Schemas are stable-ABI safe, so they live
    in the STABLE_TORCH_LIBRARY fragment (csrc/libtorch_stable/moe/
    torch_bindings.cpp)."""
    cfg_sig = ", int config_id" if tunable else ""
    return (
        f"  m.def(\n"
        f'      "{symbol}(Tensor activations_in,"\n'
        f'      "Tensor router_logits,"\n'
        f'      "Tensor expert_weights_up, Tensor expert_scales_up,"\n'
        f'      "Tensor expert_weights_down, Tensor expert_scales_down,"\n'
        f'      "Tensor! activations_out, Tensor! scratchpad,"\n'
        f'      "int top_k, int scoring_func, bool renormalize,"\n'
        f'      "Tensor? expert_bias, float routed_scaling_factor'
        f'{cfg_sig}) -> ()");\n'
    )


def _impl_reg(symbol):
    """The m.impl registration for one op.  The *_impl functions take
    torch::stable::Tensor (see the stable-ABI port), so they are TORCH_BOX'd
    into a STABLE_TORCH_LIBRARY_IMPL block in
    csrc/moe/moe_monokernel/moe_wrapper.cu (next to where the X-macro defines
    them)."""
    return f'  m.impl("{symbol}", TORCH_BOX(&{symbol}_impl));\n'


def _infix_ops(infix):
    """(named op, tunable op) symbol pair for one shape infix."""
    return (
        f"moe_monokernel_topk_BS8_{infix}_BlockFP8_WGMMA_TMA",
        f"moe_monokernel_topk_BS8_{infix}_tunable",
    )


def _shape_symbols(shapes):
    """Yield (symbol, tunable) for every op across all shapes (named + tunable,
    plus legacy-name aliases and the opt-in BS16 named/tunable ops)."""
    for s in shapes:
        for infix in (cpp_name(s), legacy_infix(s)):
            if not infix:
                continue
            named, tun = _infix_ops(infix)
            yield named, False
            yield tun, True
        if s.get("bs16"):
            nm = cpp_name(s)
            yield (f"moe_monokernel_topk_BS16_{nm}_BlockFP8_WGMMA_TMA"), False
            yield (f"moe_monokernel_topk_BS16_{nm}_tunable"), True


def emit_defs(shapes):
    """m.def schemas only — included inside the stable library fragment."""
    out = [GEN_HEADER]
    for symbol, tunable in _shape_symbols(shapes):
        out.append(_def(symbol, tunable))
    return "\n".join(out)


def emit_impls(shapes):
    """m.impl registrations only — included inside a regular TORCH_LIBRARY_IMPL
    in moe_wrapper.cu (full-libtorch ABI)."""
    out = [GEN_HEADER]
    for symbol, _tunable in _shape_symbols(shapes):
        out.append(_impl_reg(symbol))
    return "\n".join(out)


def emit_python(data):
    """Python dispatch metadata: (E,N,K)->op names, raw-upproj cfg ids, tuner
    SHAPE_OF_MODEL + MODELS rows.  N here is the FUSED gate+up dim = 2*N_half,
    matching how _custom_ops.py / fp8.py see the weight tensor."""
    shapes = data["shapes"]
    out = [PY_GEN_HEADER]
    out.append(
        '"""Generated monokernel shape registry. Imported by '
        "_custom_ops.py and\nthe tuner. Keys use the FUSED N (2*N_half) "
        'as the weight tensors expose it."""\n'
    )
    out.append("from typing import Any\n")
    rows = []
    for s in shapes:
        nm = cpp_name(s)
        uch_by_cfg = {c["id"]: uch_of(s, c["dct"], c) for c in s["configs"]}
        raw_ids = sorted([cid for cid, u in uch_by_cfg.items() if u >= 2])
        all_raw = all(u >= 2 for u in uch_by_cfg.values())
        # Per-config knob dicts (id-keyed) so the tuner reads configs straight
        # from the registry instead of re-parsing the C++ X-macro tables.
        configs = {
            c["id"]: dict(
                grid=c["grid"],
                down_col_tile=c["dct"],
                k_step_up=c["kup"],
                k_step_down=c["kdn"],
                up_w_slots=c["slots"],
                up_col_halves=uch_by_cfg[c["id"]],
                down_pipe_depth=(config_dpd_arg(c) or 2),
                down_weight_slots=(config_dws_arg(c) or config_dpd_arg(c) or 2),
            )
            for c in s["configs"]
        }
        row = dict(
            key=s["key"],
            aliases=s.get("aliases", []),
            E=s["E"],
            N_half=s["N"],
            K=s["K"],
            N_fused=2 * s["N"],
            default_top_k=s["default_top_k"],
            display_name=s["display_name"],
            cpp=nm,
            named_op=f"moe_monokernel_topk_BS8_{nm}_BlockFP8_WGMMA_TMA",
            named_op_bs16=(
                f"moe_monokernel_topk_BS16_{nm}_BlockFP8_WGMMA_TMA"
                if s.get("bs16")
                else None
            ),
            tunable_op=f"moe_monokernel_topk_BS8_{nm}_tunable",
            tunable_op_bs16=(
                f"moe_monokernel_topk_BS16_{nm}_tunable" if s.get("bs16") else None
            ),
            bs16_config_ids=bs16_config_ids(s),
            config_macro=f"MONO_CONFIGS_{nm}",
            configs=configs,
            raw_upproj_config_ids=raw_ids,
            all_raw=all_raw,
        )
        # Optional routing metadata (runtime args to the kernel, recorded per
        # shape so the accuracy/tuning harness exercises the serving routing).
        for opt in (
            "scoring_func",
            "use_expert_bias",
            "routed_scaling_factor",
            "up_col_halves",
        ):
            if s.get(opt) is not None:
                row[opt] = s[opt]
        rows.append(row)
    # repr() (not json.dumps) so booleans render as Python True/False.
    import pprint

    out.append(
        "SHAPES: list[dict[str, Any]] = "
        + pprint.pformat(rows, indent=4, width=88, sort_dicts=False)
    )
    out.append("")
    out.append("# (E, N_fused, K) -> row, for O(1) dispatch.")
    out.append("BY_ENK = {(r['E'], r['N_fused'], r['K']): r for r in SHAPES}")
    out.append("# alias / shape-name -> row (e.g. '35b', 'qwen3.5_122b').")
    out.append("BY_NAME = {a: r for r in SHAPES for a in ([r['key']] + r['aliases'])}")
    out.append("")
    # ── helper API consumed by _custom_ops.py / fp8.py / the tuner ──────────
    out.append('''
def row_for(E, N_fused, K):
    """Registry row for a fused-(E, N, K) shape, or None if unsupported.
    N_fused is the gate+up dim (2 * moe_intermediate_size)."""
    return BY_ENK.get((E, N_fused, K))


def is_supported(E, N_fused, K):
    return (E, N_fused, K) in BY_ENK


def named_op_name(E, N_fused, K):
    r = BY_ENK[(E, N_fused, K)]
    return r["named_op"]


def tunable_op_name(E, N_fused, K):
    r = BY_ENK[(E, N_fused, K)]
    return r["tunable_op"]


def config_is_raw_upproj(E, N_fused, K, config_id):
    """True if the selected config uses the raw two-TMA up-proj (UCH>=2) and
    therefore must NOT be fed Python-interleaved weights.  Shape-agnostic:
    derived from the registry's per-shape raw-config-id set."""
    if config_id is None or config_id < 0:
        return False
    r = BY_ENK.get((E, N_fused, K))
    if r is None:
        return False
    return r["all_raw"] or (config_id in set(r["raw_upproj_config_ids"]))


def resolve_config_id(E, N_fused, K, env_value):
    """Parse a MONOKERNEL_CONFIG env string into a config id for this shape.
    Forms: bare int (any shape) | name:id (35b/122b/...) | E{E}N{N}K{K}:id
    (N here is N_fused).  Returns -1 (shipped default) if unset/unmatched."""
    raw = (env_value or "").strip()
    if not raw:
        return -1
    if raw.lstrip("-").isdigit():
        return int(raw)
    r = BY_ENK.get((E, N_fused, K))
    names = set()
    if r is not None:
        names = {r["key"].lower(), *[a.lower() for a in r["aliases"]]}
    enk_key = f"e{E}n{N_fused}k{K}"
    for part in raw.split(","):
        if ":" not in part:
            continue
        key, _, val = part.partition(":")
        key = key.strip().lower()
        if (key in names or key == enk_key) and val.strip().lstrip("-").isdigit():
            return int(val.strip())
    return -1
''')
    return "\n".join(out)


# ── driver ──────────────────────────────────────────────────────────────────

OUTPUTS = {
    "dims_generated.inc": ("cpp", emit_dims),
    "config_table_generated.inc": ("cpp", emit_config_table),
    "wrapper_generated.inc": ("cpp", emit_wrapper),
    "ops_generated.inc": ("cpp", emit_ops),
    "defs_generated.inc": ("cpp", emit_defs),
    "impls_generated.inc": ("cpp", emit_impls),
    "monokernel_shapes.py": ("py", emit_python),
}


def out_dir_for(fn):
    """C++ .inc files live under generated/; the Python registry must be
    importable from the installed vllm package, so it lands in PY_PKG_DIR."""
    return PY_PKG_DIR if fn.endswith(".py") else GEN_DIR


def render(data):
    shapes = data["shapes"]
    rendered = {}
    for fn, (_kind, emitter) in OUTPUTS.items():
        rendered[fn] = emitter(data) if emitter is emit_python else emitter(shapes)
    return rendered


def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if any generated file is stale (CI guard)",
    )
    ap.add_argument(
        "--print",
        dest="section",
        choices=["dims", "config_table", "wrapper", "ops", "defs", "impls", "python"],
        help="print one section to stdout and exit (no files written)",
    )
    args = ap.parse_args()

    data = load_shapes()

    if args.section:
        key = {"python": "monokernel_shapes.py"}.get(
            args.section, f"{args.section}_generated.inc"
        )
        print(render(data)[key])
        return

    os.makedirs(GEN_DIR, exist_ok=True)
    rendered = render(data)
    stale = []
    for fn, content in rendered.items():
        path = os.path.join(out_dir_for(fn), fn)
        if os.path.exists(path):
            with open(path) as f:
                old = f.read()
        else:
            old = None
        if old != content:
            stale.append(fn)
            if not args.check:
                with open(path, "w") as f:
                    f.write(content)
    if args.check:
        if stale:
            print(
                f"STALE generated files (re-run gen_shapes.py): {stale}",
                file=sys.stderr,
            )
            sys.exit(1)
        print("generated files up to date")
    else:
        for fn in rendered:
            print(f"  {os.path.relpath(os.path.join(out_dir_for(fn), fn), ROOT)}")
        print(f"wrote {len(rendered)} files ({len(stale)} changed: {stale or 'none'})")
        print(f"shapes: {[s['key'] for s in data['shapes']]}")


if __name__ == "__main__":
    main()
